import type { Metadata } from 'next'
import './globals.css'
import I18Provider from '@/provider/I18Provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <I18Provider>{children}</I18Provider>
      </body>
    </html>
  )
}
